### ISSUE TITLE
How to implement a new model in another language

### ISSUE THREAD

**Issue by jhoelzl** [ottokart/punctuator#10]
Hi,

i really appreciate your work, I want to test the script on non punctuated English or German text. So, i guess i have to make a new model with that language.

Can you briefly describe the tasks to implement a new model in a specific language?

Regards,
Josef

**Comment by ottokart** [comment]
Hi!

Thanks for the appreciation! 
To train a new entirely text based model, you would need to obtain and prepare a text corpus in the target language. The process is not much different from the one of preparing a language modeling dataset. An example of the end result can be seen, for example, [here.](https://github.com/ottokart/punctuator/blob/master/raw_data/dev.txt)

If you want to include pause duration feature as well, then things get more complicated, unless a suitably annotated dataset is readily available.

By the way, there's now an [improved version](https://github.com/ottokart/punctuator2) available.
It also has an English [demo](http://bark.phon.ioc.ee/punctuator) that you can try.

**Comment by jhoelzl** [comment]
Thank you for your support, i will definitly try the improved version. The English demo looks very promising!
