### ISSUE TITLE
Minor issue in running punctuator after training

### ISSUE THREAD

**Issue by ngoel17** [ottokart/punctuator#3]
Please see the following diff that I had to do to make the punctuate code work correctly.

21c21
## <                 word_index = utils.input_word_index(net.t_lstm.in_vocabulary, word)

> ```
>             word_index = utils.input_word_index(net.in_vocabulary, word)
> ```

**Comment by ottokart** [comment]
Thanks for reporting! Fixed the problem, but in a slightly different way.
